server:
  port: 8080

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    register-with-eureka: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: clientService
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/clients/**
        - id: particularsService
          uri: lb://PARTICULAR-SERVICE
          predicates:
            - Path=/particulars/**